"""empty message

Revision ID: 3314b3efd0c8
Revises: 
Create Date: 2021-12-08 01:17:24.163163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3314b3efd0c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rand_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_rand', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_rand')
    )
    op.create_table('res_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_res', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_geo', sa.Integer(), nullable=False),
    sa.Column('name_rand', sa.String(), nullable=False),
    sa.Column('Type1', sa.Text(), nullable=True),
    sa.Column('Type2', sa.Text(), nullable=True),
    sa.Column('add', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_geo'], ['rand_id.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('res',
    sa.Column('id_geo', sa.Integer(), nullable=False),
    sa.Column('id_res', sa.Integer(), nullable=False),
    sa.Column('loc_street', sa.Text(), nullable=True),
    sa.Column('add', sa.Text(), nullable=False),
    sa.Column('res_url', sa.Text(), nullable=True),
    sa.Column('review_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_geo'], ['rand_id.id'], ),
    sa.ForeignKeyConstraint(['id_res'], ['res_id.id'], ),
    sa.PrimaryKeyConstraint('id_res')
    )
    op.create_table('res_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_res', sa.Integer(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.Column('Rating', sa.Text(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_res'], ['res_id.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('res_review')
    op.drop_table('res')
    op.drop_table('rand')
    op.drop_table('res_id')
    op.drop_table('rand_id')
    # ### end Alembic commands ###
